[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "foris-controller"
dynamic = ["version"]
description = "An program which is placed in top of a message bus and translates requests to commands for backends."
readme = "README.rst"
license = { "file" = "COPYING" }
authors = [
    { name = "CZ.NIC, z.s.p.o. (http://www.nic.cz/)", email = "packaging@turris.cz" },
]
requires-python = ">=3.10"
dependencies = [
    "foris-schema",
    "pbkdf2",
    "python-prctl",
    "python-slugify",
    "svupdater",
    "turris-timezone",
    "turrishw",
]

[tool.hatch.metadata]
allow-direct-references = true


[project.optional-dependencies]
client-socket = [
    "foris-client",
]
dev = [
    "cookiecutter",
    "pre-commit",
    "ruff",
	"tox",
]
mqtt = [
    "paho-mqtt",
]
tests = [
    "foris-client",
    "foris-controller-testtools >= 3.0.0",
    "paho-mqtt",
    "pytest",
    "ubus",
    "tox",
]
ubus = [
    "ubus",
]
zeroconf = [
    "ifaddr",
    "paho-mqtt",
    "zeroconf",
]

[project.scripts]
foris-controller = "foris_controller.controller.__main__:main"
foris-notify = "foris_controller.notify.__main__:main"

[project.entry-points.foris_controller_modules]
about = "foris_controller_modules.about"
dns = "foris_controller_modules.dns"
guest = "foris_controller_modules.guest"
introspect = "foris_controller_modules.introspect"
lan = "foris_controller_modules.lan"
maintain = "foris_controller_modules.maintain"
networks = "foris_controller_modules.networks"
password = "foris_controller_modules.password"
remote = "foris_controller_modules.remote"
router_notifications = "foris_controller_modules.router_notifications"
system = "foris_controller_modules.system"
time = "foris_controller_modules.time"
updater = "foris_controller_modules.updater"
wan = "foris_controller_modules.wan"
web = "foris_controller_modules.web"
wifi = "foris_controller_modules.wifi"

[project.urls]
Homepage = "https://gitlab.nic.cz/turris/foris-controller/foris-controller"

[tool.hatch.version]
path = "foris_controller/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/foris_controller",
    "/foris_controller_backends",
    "/foris_controller_modules",
]
[tool.hatch.build.targets.wheel]
include = [
    "/foris_controller",
    "/foris_controller_backends",
    "/foris_controller_modules",
]
