[tox]
envlist = py{310,311}
skip_missing_interpreters = true
minversion = 4.4.0

[testenv]
deps =
	pytest
	pytest-cov
	foris-controller-testtools
	paho-mqtt
	ubus
	foris-client
	{toxinidir}/tests/blackbox/test_modules/echo
description = Run the tests with pytest
package = wheel
wheel_build_env = .pkg
extras = tests
commands = pytest {posargs}

[pytest]
addopts = --verbose
testpaths = tests
python_files = test_*.py
console_output_style = count
norecursedirs = tests/blackbox/helpers
pytest_plugins = foris_controller_testtools
