#!/bin/sh

required_opt=$(cat /tmp/foris-controller-tests-wifi-detect-opt)

if [ "$required_opt" != "$1" ] ; then
	exit 1
fi


cat > /tmp/uci_import <<EOF
package 'wireless'

config wifi-device  radio0
        option type     mac80211
        option channel  36
        option country  'CZ'
        option hwmode   11a
        option macaddr  '99:88:77:66:55:44'
        option htmode   VHT80
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 1

config wifi-iface
        option device   radio0
        option network  lan
        option mode     ap
        option ssid     Turris
        option encryption none

config wifi-device  radio1
        option type     mac80211
        option channel  11
        option country  'CZ'
        option hwmode   11g
        option path     'soc/soc:pcie-controller/pci0000:00/0000:00:03.0/0000:03:00.0'
        option htmode   HT20
        # REMOVE THIS LINE TO ENABLE WIFI:
        option disabled 1

config wifi-iface
        option device   radio1
        option network  lan
        option mode     ap
        option ssid     Turris
        option encryption none

EOF

if [ "$1" = "config" ] ; then
	cat /tmp/uci_import | uci -c "$DEFAULT_UCI_CONFIG_DIR" import
	exit 0
else
	cat /tmp/uci_import | tail -n +1
fi

#rm /tmp/uci_import
